import Head from "next/head";
import {
  Container,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/lib/axios";
export default function Home() {
  const [products, setProducts] = useState([]);

  const fetchingData = async () => {
    try {
      const { data } = await axiosInstance.get("/products");
      setProducts(data.datas);
    } catch (error) {
      console.log(error);
    }
  };

  const renderDataProducts = () => {
    return products.map((product) => {
      return (
        <Tr key={product.id}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.description}</Td>
          <Td>Rp. {Number(product.price).toLocaleString("id-ID")}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };

  useEffect(() => {
    fetchingData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TableContainer>
          <Table variant="striped">
            <Thead>
              <Tr>
                <Th>Id</Th>
                <Th>name</Th>
                <Th>description</Th>
                <Th>price</Th>
                <Th>image</Th>
              </Tr>
            </Thead>
            <Tbody>{renderDataProducts()}</Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  );
}
