import Head from "next/head";
import { Container, Heading } from "@chakra-ui/react";
import axios from "axios";
import { useEffect } from "react";

export default function Home() {
  const localUrl = process.env.localUrl;

  const fetchingData = async () => {
    try {
      const { data } = await axios.get(`${localUrl}/products`);
      console.log(data);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchingData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello world</Heading>
        </Container>
      </main>
    </>
  );
}
